# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f93bf13d57e885ff0e5b3201a67bca7b498bfb93bb9e1e0d6c9bf0254800a28d2c78c1f9d832c3938273fd1430927a4bbb9f6f266db8afc7232c77ca6cb93b

test:
  secret_key_base: 4fe144f4d0e9143daeabacaf14711d5a2635e72eb9c060bbc3162a8d2d1165a28ee80e4a0d635cb28d4769fddbbba04755cfbdcde725d32fcd7ded84d2efe603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
